### ISSUE TITLE
First meeting

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022-pointer#3]
In order to make progress on this investigation effort, it seems like the next step should be a meeting between stakeholders. @flackr have you identified the right people, and you can organize this?

**Comment by smaug----** [comment]
I might be interested in the pointer events interop, though it isn't very clear to me what this all is about :)

cc @EdgarChen

**Comment by EdgarChen** [comment]
I am also interested in the pointer event interop. :)

**Comment by flackr** [comment]
Thanks! I just sent an e-mail to coordinate scheduling the first meeting to everyone who's expressed interest so far.

**Comment by flackr** [comment]
I've scheduled a tentative first meeting based on everyone's feedback for May 26th at 12 PT. The rough agenda is the following:
1. Discuss what we will consider success for this interop area. Based on prior concerns that the failings pointerevents tests were not well correlated to real world problems, how do we ensure we test the right things?
2. Decide how will we track progress towards and measure success? This will likely be a breakdown of the work needed into concrete steps with the end goal being a list of tested real world interop cases, and a list of bugs we would like to address but may require additional infrastructure or spec agreement.
3. Choose a next meeting time :-)

**Comment by flackr** [comment]
We just had our first meeting where we went over each of the topics.

1. There were two main areas discussed here:
   - In terms of getting the issues that affect real world developers we believe that due to sourcing bugs and reaching out to developers we will have a much better signal for real world issues.
   - In cases where mouse events can test for the same expectation as well as touch or stylus, we agreed to only include the mouse event on the test list as it will be more widely tested and the mouse result should in most cases be the same as the touch result if touch was supported.
2. Broadly speaking the work will be three phases:
   1. Discovery of issues - we will add to [the list](https://docs.google.com/spreadsheets/d/1K3lnen0hP0T3z7lDmUnTtTrA-qWJ5JVTvkuvhV8AQhY/edit#gid=0) issues from bug tracker lists, framework / partner lists, outreach etc.
   2. Triaging the issues list - This will involve removing duplicates and establishing the current state of the issues. In particular an issue may need agreement on desired behavior, need specification, need tests, or be covered by an existing test.
   3. Specifying behavior and adding tests - For issues which aren't currently covered by tests we'll progress them through agreement on behavior, spec changes, and adding the necessary tests (possibly determining that we can't have automated test coverage e.g. if lacking testdriver support).
3. The next meeting will be aiming for somewhere around 2-3 months out. I will be sending out a form to gather possible meeting dates to confirm on the exact date.

**Comment by foolip** [comment]
This first meeting happened, closing this issue.
